/*INSERT INTO TAREFA VALUES(1, 'Codificar a demanda.','Codificar' );*/
/*SELECT * FROM TAREFA;
  SELECT * FROM ITEM ;
  SELECT * FROM "schema_version";
  */

CREATE TABLE ITEM(CODIGO INT PRIMARY KEY , DESCRICAO VARCHAR(100));
INSERT INTO ITEM VALUES(1,'ITEM 1');
INSERT INTO ITEM VALUES(2,'ITEM 2');
INSERT INTO ITEM VALUES(3,'ITEM 3');